### ISSUE TITLE
Master Checklist

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#1]
# Wave Interference Port Master Checklist

## Design
- [x] **Sim folder and design doc created** (Date: 10/05/2017) 
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Legacy sim docs/info gathered**
  - [x] Sim suggestions doc reviewed
  - [x] Unfuddle tickets reviewed
- [x] **Learning goals and standards identified** (Date: 10/19/2017)
- [x] **Design concept complete**  (Date: 03/08/2018)
- [x] **Wireframes complete** (Date: 03/09/2018) 
- [x] **Mockups complete** (Date: 05/16/2018) 
  - [x] Mockups checked for colorblind and greyscale
- [ ] **Features for PhET-iO discussion** 
- [x] **Interviews complete** (Date: 12/11/18) 
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 12/09/2018) 
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Auxilary screenshots (up to 3 additional) - #328 
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide created, uploaded, and added to sim design folder - #200 
  - [x] Sim primer draft - #337 
  - [x] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive - #336 
  - [x] LoL [metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)
- [ ] **Post-publication items** 
  - [ ] Add to Edmodo
  - [ ] Add to [Gooru](http://gooru.org/PhET/content/resources), remove legacy version (signed in as phethelp)
 - [x] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [x] Sim primer (create issue, publish ideally within 1 month of live sim) - #337 
  - [ ] Hold postmortem if applicable (Date: //) 

## Implementation
- [x] **Repository created** (Date: 10/05/2017)
  - [x] Simulation added to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] simula-rasa used to create project skeleton
  - [x] README.md created using `grunt unpublished-readme`
  - [x] Collaborators added (such as QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to chipper/data/ filesr
  - [x] Port existing strings (IF ANY) and commit to the GitHub repo (auto-ported strings from Java and Flash sims can
  be found in babel/autoport). The strings should be deleted from babel/autoport and @jbphet should immediately be asked.  **At Dev Meeting Jan 31, 2019 we decided we are no longer doing this step.**
- [x] **Development started** (Date: 10/05/2017)
- [x] **Sim is "feature complete"** (Date: 1/15/2017 for 1.0 features, Diffraction screen not complete) 
- [x] **Code review completed** (Date: 12/19/18) 
- [x] **Pre-publication items** 
  - [x] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/doc/qa-book.md#screenshots))
  - [x] Verify credits (should include @clmccutchan), see #285
- [x] **Published** (Date: 1/30/2019) 
  - [x] README.md updated using `grunt published-readme` (in master and release branch)
  - [x] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)

## QA
- [ ] **Legacy sim tested for bugs**; issues reported in repo
- [x] **Dev testing started** (Date: 12/12/2018) 
- [x] **Dev testing complete** (Date: 01/23/2019) 
- [x] **First RC published** (Date: 01/28/2019)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 01/29/2019)

# Wave Interference 2.0

### Design
- [x] **Learning goals and standards identified** (Date: 10/19/2017)
- [x] **Design concept complete**  (Date: 08/12/2017)
- [x] **Wireframes complete** (Date: 08/12/2017) 
- [x] **Mockups complete** (Date: 03/01/2019) 
  - [x] Mockups checked for colorblind and greyscale
- [ ] **Features for PhET-iO discussion** 
- [x] **Interviews complete** (Date: 06/21/2019) 
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 06/21/2019) 
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Auxilary screenshots (up to 3 additional) - #427 
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide created, uploaded, and added to sim design folder  - #410  
  - [x] Sim primer draft - #337 
  - [x] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive  - https://github.com/phetsims/wave-interference/issues/456
  - [x] LoL [metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use) - https://github.com/phetsims/wave-interference/issues/456
- [ ] **Post-publication items** 
  - [x] Add to Edmodo
  - [x] Add to [Gooru](http://gooru.org/PhET/content/resources), remove legacy version (signed in as phethelp)
  - [x] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) - https://github.com/phetsims/wave-interference/issues/456
  - [x]  Sim primer (create issue, publish ideally within 1 month of live sim) - #337 
  - [ ] Hold postmortem if applicable (Date: //) 

### Implementation
- [ ] **Development started** (Date:  )
- [x] **Sim is "feature complete"** (Date: 07/15/2019) 
- [x] **Code review completed** (Date: 06/25/2019) - #376
- [x] **Pre-publication items** 
  - [x] Verify credits - #428 
- [x] **Published** (Date: 09/23/2017) 

### QA
- [x] **Dev testing started** (Date: 05/23/2019) 
- [x] **Dev testing complete** (Date: 08/06/2019) 
- [x] **First RC published** (Date: 08/13/2019)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 09/18/2019)

**Comment by pixelzoom** [comment]
It looks like this checklist has not been maintained by @samreid @arouinfar or @KatieWoe.   I've started code review in https://github.com/phetsims/wave-interference/issues/259, and this issue is not providing info needed to complete that checklist.

**Comment by KatieWoe** [comment]
I was unaware of this.  QA section updated.

**Comment by arouinfar** [comment]
The checklist is now up to date, but reflects the progress for the screens which will be included in the 1.0 release. Leaving assigned to @ariel-phet to add a section for the 2.0 release.

**Comment by pixelzoom** [comment]
Code review completed today, see #259, so I checked it off here in the master checklist.

**Comment by arouinfar** [comment]
@ariel-phet the remaining items are yours. We also need an additional, pared-down checklist for 2.0.

**Comment by samreid** [comment]
@arouinfar or @ariel-phet any other pre-publication items to do before I publish wave-interference 2.0?  I noticed that the screenshot in the branch already shows the diffraction screen:
https://github.com/phetsims/wave-interference/blob/7ebcb1ae70106ca93d7d430d4a6cf77f23a0fa3b/assets/wave-interference-screenshot.png

**Comment by arouinfar** [comment]
@samreid I don't think there's anything blocking 1.0.

I will make a 2.0 section of the checklist covering the design issues as I make the sim live.  We should probably do the same for Implementation and QA too.

**Comment by samreid** [comment]
> @samreid I don't think there's anything blocking 1.0.

I presume you meant there's nothing blocking today's publication of 2.0.  Please correct me if this is wrong.

**Comment by arouinfar** [comment]
@samreid sorry, yes, I meant 2.0. 🤦‍♀ 

I've edited the comment.

**Comment by samreid** [comment]
Wave Interference 2.0 is published, @arouinfar can you please address post-publication steps?

**Comment by arouinfar** [comment]
The remaining unchecked items are not applicable (e.g. post-mortem, PhET-iO discussion), so this can be closed.
