### ISSUE TITLE
Items for Teacher Tips

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#200]
For #1 

- [x] Apparent interference pattern in the screen - #171 
- [x] Intensity curve is not perfect - #163 
- [x] `?theory` - #74 
- [x] Plane wave source is generic - #54 
- [x] Absorbing boundary conditions - #197 
- [x] Nature of plane wave model and changing amplitude - #210 
- [x] Spatial averaging in graph - #137, #234 
- [x] Color mapping - #142 
- [x] Black background for light - #258 
- [x] Temporal step size - #226 
- [x] Screen & intensity graph are time-averaged - #208 
- [x] Light amplitude is attenuated so it is parallel to other scenes, though blackness is used to represent a vacuum, so no attenuation would technically occur. Given length scale of lattice (a few wavelengths) you wouldn't expect to see much attenuation of light, even in an absorptive medium.
- [x] Lattice resets (or partially resets) when barrier moves, source separation changed, frequency changed (slits/light) - #176, #316, #309 

Note to self: The legacy sim does not have a Teacher Tips document.

I'll edit this comment as I think of/encounter issues which will need to be documented in the Tips. Marking as `status:on-hold` until this sim gets closer to publication.

**Comment by arouinfar** [comment]
Since we're nearing the Jan 31 deadline, I'll remove `status:on-hold`.

**Comment by arouinfar** [comment]
Teacher Tips have been completed.
