### ISSUE TITLE
Plan for publication for wave-interference 2.0 with diffraction

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#372]
This simulation is getting closer to being ready for publication.  Some steps we will need to take (not necessarily in chronological order)

- [x] Preliminary dev testing (could do early dev testing before other parts complete), see https://github.com/phetsims/QA/issues/322
- [x] Code review #376
- [x] Interviews on the diffraction screen https://github.com/phetsims/wave-interference/issues/409
- [x] Finalize design, pixel polishing, memory testing and discovered QA issues, marked with this label https://github.com/phetsims/wave-interference/issues?q=is%3Aissue+is%3Aopen+label%3Awave-interference%3A2.0.  As of July 15, this consists of only https://github.com/phetsims/scenery-phet/issues/513
- [x] Review of changes for Waves Intro, see https://github.com/phetsims/wave-interference/issues/414
- [x] 2nd round of dev testing, see https://github.com/phetsims/QA/issues/389
- [ ] RC testing

Also, this simulation shares code with Waves Intro, which is also in development.  So we will need to coordinate efforts and make sure Waves Intro is not in an intermediate state when we are ready to branch SHAs for this sim.

@ariel-phet did I forget anything for this issue?  Are the checkboxes listed in the correct order?

**Comment by ariel-phet** [comment]
@samreid, we need to do some interviews on the diffraction screen, but otherwise things look good.

**Comment by samreid** [comment]
I changed package.json over to 2.0 series for subsequent dev deploys.

**Comment by samreid** [comment]
Dev test published here: https://github.com/phetsims/QA/issues/371

**Comment by samreid** [comment]
RC testing is proceeding in https://github.com/phetsims/wave-interference/issues/441, closing.
